### ISSUE TITLE
Pimatic Updates

### ISSUE THREAD

**Issue by DerGrafausB** [pimatic/pimatic#1056]
Since 7 weeks there are no updates for pimatic or for any plugin.
Something wrong?

**Comment by mwittig** [comment]
Well, it depends on which plugins you're using. The pimatic core and front have not been updated since early January. Various plugin have been updated I am aware of, but it may node of these is on your list. In case of doubt youn can checked the published versions on npmjs.com. You may also wabt to restart pimatic (if you done this already) as we had an update issue about three weeks ago.

I am closing this now as the update server is working as expected.

**Comment by leader21** [comment]
just for info : i recently had a similar issue and restarted the pi. after that there were plugins for update and all went fine again.
