### ISSUE TITLE
SSL-Certificate - New Certificate for Chrome and other new browsers

### ISSUE THREAD

**Issue by UltimateGER** [pimatic/pimatic#1093]
Hello,

since updates of chrome and other browsers i can´t make secure connection to my pimatic on raspberry pi.

Thanks for your great work with pimatic and the plugins.

**Comment by mwittig** [comment]
- What kind of certificate do you use?
    * Self-signed certificate, or
    * certificate signed by a trested CA, e.g. "let's encrypt"

- Did you check the validity date of the certificate? Is it still valid?
- What kind of error message do you get? 
    * you can also send a screenshot if that's easier for you

**Comment by UltimateGER** [comment]
Hello,

i have created a own certificate with ssl-setup. Its RSA512 with 4096 bit key.
Date of certificate and the computers are valid.
I have read in a forum that the "subjectAltName" must be in the certificate. But all trys with ssl-setup to add an alias are mistakes.

![fehler](https://user-images.githubusercontent.com/37457817/37565095-da2f0ef4-2aa2-11e8-945a-4886bf719cee.jpg)

**Comment by Devqon** [comment]
Is there any resolution for this? I have followed the guide on https://pimatic.org/guide/getting-started/remote-ssl/ , but get the same errors on Chrome.

**Comment by mwittig** [comment]
This is expected behaviour as the setup using the link above creates a self-signed certificate which means it has not been created by trusted CA. Generally, you can manually add the certificate as a trustpoint, but this is not recommended. Note, the error message above is actually a warning message. If you click on "Erweitert" / "Advanced" and grant the connection it will work anyway and you will not see the error message popping up again for some time. However, the better approach is to get a proper certificate. These days it is popular to use "let's encrpyt" for this purpose it is free of charge. See https://forum.pimatic.org/topic/1037/pimatic-with-trusted-ssl-certificate-from-letsencrypt for example.

**Comment by Devqon** [comment]
@mwittig alright thank you, seems that it has to do with my shortage of knowledge of SSL certificates.
Could this warning be added to the [howto-ssl](https://pimatic.org/guide/getting-started/remote-ssl/) for future users?
