### ISSUE TITLE
Plugins ERROR

### ISSUE THREAD

**Issue by akicker** [pimatic/pimatic#1175]
Updating the pluginlist error
api.pimatic.org/plugins  results in 502 Bad Gateway !!!

**Comment by akicker** [comment]
all pages api.pimatic.org are not reachable :-(

**Comment by fbeek** [comment]
As already said in some other issues: Pimatic is dead

There are a lot of Problems because of the old NodeJs Version  (LARGE SECURITY ISSUE) and the fragile update mechanisms.
Also there is no active core development any more as you can see in the commit history.

The best thing you can do is to switch to Homeassistant or any other Homeautomation Software.

**Comment by akicker** [comment]
My pimatic will stay alive for a while, because:
I did program lots of addons, which cannot be transered easyly to another system
I got it running on a pi4 running bullseye 👍
A la long i will move to Home Assistant!
