### ISSUE TITLE
Got no Frontend on mobile devices:

### ISSUE THREAD

**Issue by Neuss1987** [pimatic/pimatic#136]
It works with:
Windows 8, Windows 8.1, Vista, Linux,....

It didn't worked with:

iPhone 4 - iOS 7.1
iPhone 5c - iOS 7
Samsung GalaxyTab 2 - Android 4.2.2
Samsung GalaxyTab 2 - with Cyanogenmod  Android 4.2.2

Is there a solution how to fix it?
Pimatic:

mobile-frontend 0.7.4
pilight 0.7.1
rest-api 0.7.0

**Comment by HansKappert** [comment]
I had the same problem. It was caused by the fact that a small part was missing from the config.json under de plugin section:
{
      "plugin": "mobile-frontend"
},

I had already tried to re-install everything, but after that I copied my backed up config into the piratic-app folder, causing the same issue again. When I used the default config.json the interface was there again. Go figure :-)
