### ISSUE TITLE
[pimatic] post date in email

### ISSUE THREAD

**Issue by knudje** [pimatic/pimatic#145]
I have an event, when a door is opened, my Rpi plays a doorbell sound and i get an email. I would like to include a date time stamp in the email like in : 'door was opened at 2/5/2014 11:01'. Can I do this, and if yes, how?

**Comment by mwittig** [comment]
For the date formatting the [date-format-lite](https://www.npmjs.com/package/date-format-lite) package is used. See supported syntax below. You get the day of week by using the `w` designator. Make sure you have German locale settings set on your Raspi if you wish to have localized time information.

- **Y**     - A two digit representation of a year without leading zeros. Examples: 99 or 3
- **YY**    - A two digit representation of a year. Examples: 99 or 03
- **YYYY**  - A full numeric representation of a year, 4 digits. Examples: 1999 or 2003
- **M**     - Numeric representation of a month, without leading zeros. 1 through 12
- **MM**    - Numeric representation of a month, with leading zeros. 01 through 12
- **MMM**   - A short textual representation of a month, three letters. Jan through Dec
- **MMMM**  - A full textual representation of a month, such as January or March. January through December
- **D**     - Day of the month without leading zeros. 1 to 31
- **DD**    - Day of the month, 2 digits with leading zeros. 01 to 31
- **DDD**   - A textual representation of a day, three letters. Mon through Sun
- **DDDD**  - A full textual representation of the day of the week. Sunday through Saturday
- **H**     - 12-hour format of an hour without leading zeros. 1 through 12
- **HH**    - 12-hour format of an hour with leading zeros. 01 through 12
- **h**     - 24-hour format of an hour without leading zeros. 0 through 23
- **hh**    - 24-hour format of an hour with leading zeros. 00 through 23
- **m**     - Minutes without leading zeros. 0 through 59
- **mm**    - Minutes with leading zeros. 00 to 59
- **s**     - Seconds without leading zeros. 0 through 59
- **ss**    - Seconds with leading zeros. 00 to 59
- **S**     - Milliseconds without leading zeros. 0 through 999
- **SS**    - Milliseconds with leading zeros. 000 to 999
- **u**     - Milliseconds since the Unix Epoch (January 1 1970 00:00:00 GMT)
- **U**     - Seconds since the Unix Epoch (January 1 1970 00:00:00 GMT)
- **A**     - Ante meridiem and Post meridiem. AM or PM
- **"text"** - text, quotes should be escaped, eg '"a \\"quoted text\\"" YYYY'

### Time zone designators
- **Z**     - Time offsets from UTC in the form ±hh[:mm] Examples: +02, +02:30
- **ZZ**    - Time offsets from UTC in the form ±hh[mm] Examples:  +02,  +0230
- **ZZZ**   - Time offsets from UTC in the form ±hh:mm Examples:   +02:00, +02:30
- **ZZZZ**  - Time offsets from UTC in the form ±hhmm Examples:    +0200,  +0230


### ISO-8601
- **w**     - Day of the week. 1 (for Monday) through 7 (for Sunday)
- **W**     - Week number of year, first week is the week with 4 January in it
- **o**     - ISO-8601 year number. This has the same value as YYYY,
except that if the ISO week number (W) belongs to the previous or next year, that year is used instead
