### ISSUE TITLE
[pimatic sispmctl plugin] more than on device

### ISSUE THREAD

**Issue by hans-meier-01** [pimatic/pimatic#154]
Hello,

at the moment I control a power strip "Gembird EG-PMS2" on Pimatic. This works fine :)
Now I want to connect and control another power strip.
But I have a problem setting up this, what have I to enter into the actuator configuration and how do I assign it in "config.json".

Can you show me just give an example?

Thank you
Hans

PS: mein Deutsch ist besser ;-)

**Comment by Symmetry22** [comment]
Hey sweetpi,

i have to pull that issue up again.
I am using pimatic on an Raspi 2 Model B with the Sispmctl plugin and two Gembird EG-PMS2.
Everything worked fine until i connected the 2nd Gembird and restarted the Pi yesterday.
I am using them for controlling two different terrarium and yesterday, after a reboot of my Pi, pimatic switched the devices. I recognized it because the wrong lights were turned on when i came home. When i tested to switch them manually i saw that "Device 0" has changed to "Device 1" and otherwise.
After that i changed the device numbers in the config and everything was fine until i did a reboot of the Pi again. After that reboot the device numbers were wrong again.
That bug is just existing when rebooting the Pi. When i just restart pimatic everything is fine.
Is that a known problem?

Thanks

Alex

**Comment by incmve** [comment]
It's not pimatic but the Pi itself.
see here for a solution
http://forum.pimatic.org/topic/42/tip-homeduino-usb/2

**Comment by Symmetry22** [comment]
Thanks incmve,
i'll try that when i am back home.
Just hoping that the Pi doesn't need to reboot the next three weeks.

**Comment by sweetpi** [comment]
The trick descriped by incmve only works for homeduino. I've updated the sispmctl plugin and added a option to identify devices by there serial number. List you devices with:

```
pi@raspberrypi ~ $ sudo sispmctl -s
Gembird #0
USB information:  bus 001, device 007
device type:      4-socket SiS-PM
serial number:    01:01:XX:XX:XX
```

and use device configs like:

```
{ 
  "id": "light",
  "class": "SispmctlSwitch", 
  "name": "Lamp",
  "outletUnit": 1,
  "deviceSerial": "01:01:XX:XX:XX"
}
```
