### ISSUE TITLE
Support i2c devices like bmp085

### ISSUE THREAD

**Issue by Flowsche** [pimatic/pimatic#352]
Hey it would be nice if someone could write a module/script for i2c sensores like the bmp085 (or equal models like 180). Actually i solved this gap with the log reader and a python script, but a special module to read the pressure and the temperature of the sensor without using external tools or scripts would be great!

**Comment by mwittig** [comment]
I am closing this as, due to inactivity. Various i2c i2c plugins had been developed meanwhile. I am not sure, however, bmp085 is specifically support by one of them. Another way of integrate this is to use the log reader. See https://forum.pimatic.org/topic/490/solved-bmp085-i2c-raspbeery-pi-with-pimatic
