### ISSUE TITLE
[log-reader'] file not reading - possible bug

### ISSUE THREAD

**Issue by htca** [pimatic/pimatic#431]
I tried to use the log-reader. Unfortuneatly I was not able to get the information from the log file. I save my logfile on /home/pi/log/server.log. This file has rw for everyone (to be sure). 
I put some error statements in the "log-reader.coffee" file, to see what's wrong. But I do not "speak" the coffee language yet. In any case; I modified the following lines:

```
      # On ervery new line in the log file
      env.logger.error(@config.lines)
      @tail.on 'line', (data) =>
        env.logger.error("entering lines!")
        # check all lines in config
        for line in @config.lines
          env.logger.error(@line)
          # for a match.
          matches = new RegExp(line.match).exec(data)
          if matches?
            # If a match occures then emit a "match"-event.
            @emit 'match', line, data, matches
        return
      env.logger.error("after")
```

My config looks like:

```
    {
      "id": "waterlog",
      "name": "Waterstand",
      "class": "LogWatcher",
      "file": "/home/pi/log/server.log",
      "attributes": [
        {
          "name": "Waterstand",
          "type": "number",
          "unit": "cm"
        }
      ],
      "lines": [
        {
          "match": "Waterstand: +(.+)",
          "Waterstand": "$1"
        }
      ]
    }
```

In the log I will get the following information:

```
error [pimatic-log-reader]: after
21:18:41error [pimatic-log-reader]: [ { match: 'Waterstand: +(.+)', Waterstand: '$1' } ]
21:18:41error [pimatic-log-reader]: { Waterstand: { description: 'Waterstand', type: 'number', unit: 'cm' } }
21:18:41error [pimatic-log-reader]: { id: 'waterlog', name: 'Waterstand', class: 'LogWatcher', file: '/home/pi/log/server.log', attributes: [ { name: 'Waterstand', type: 'number', unit: 'cm' } ], lines: [ { match: 'Waterstand: +(.+)', Waterstand: '$1' } ] }
```

If I follow the code, It seems that the file is not opened by "tail.on", because "entering lines!" does not show up in the log. Does anyone have any clue, what can be wrong?

**Comment by sgoetze** [comment]
On 26 Dec 2014 @sweetpi commented that v. 0.8.1 would read the logfile at pimatic startup to get valid attribute values from the beginning. Now for me v. 0.8.5. does not do this. On pimatic startup all attributes of logwatcher have zero values. After some minutes the right values appear. But the zero values are written to the database and are shown in the graphs as glitches. For big gas consumtion values (>10000) with little changes (10-20 a day) these zero values after each restart of pimatic make the graph unuseable because of the spreaded Y-scale 0..10xxx.

I asked @Yves911, he has the zero values at startup too. Please @sweetpi - look at this problem again.

**Comment by sweetpi** [comment]
@sgoetze Could you open a new issue and post your config and log format?
