### ISSUE TITLE
Cannot get /

### ISSUE THREAD

**Issue by neographikal** [pimatic/pimatic#468]
When I try to access pimatic it gives me a cannot GET / notice. It is running though, an existing browser on my phone that has cached the site still works, but a fresh browser it does not load the site. 

23:30:56.947 [pimatic] info: listening for http-request on port 8080...
23:30:56.957 [pimatic-pilight] info: pilight: found pilight server 192.168.2.32:40694, trying to connect
23:30:56.963 [pimatic-pilight] info: connected to pilight-daemon
neo@neo-linux:/opt/pimatic-app$

**Comment by htca** [comment]
I had the same problem a few weeks ago. Please have a look at your available diskspace; removing the pimatic directory and reinstalling solved my problem.

**Comment by sweetpi** [comment]
```
cd pimatic-app
sudo rm -rf node_modules/pimatic-mobile-frontend
```

and restart pimatic should fix the problem. A error log of the update would be create? Do you have still the log files?

**Comment by neographikal** [comment]
Okay that is weird, I don't have that dir??

neo@neo-linux:/opt/pimatic-app/node_modules$ ls
pimatic       pimatic-pilight   pimatic-sunrise
pimatic-cron  pimatic-redirect  sqlite3
neo@neo-linux:/opt/pimatic-app/node_modules$

**Comment by sweetpi** [comment]
Then just restarting should be enough. It should autoinstall the mobile-frontend (if its in your config).

**Comment by neographikal** [comment]
Too bad, it doesn't. Where should it be, it seems like Pimatic just ate my
mobile frontend ghehe.



Met vriendelijke groet,

Sander van de Geijn
http://www.neofoto.nl/

**Comment by sweetpi** [comment]
It would be a good idea to post the logs...

**Comment by htca** [comment]
I backed up my config.json
I removed my complete pimatic-app directory
Than I reinstalled the pimatic again and copied the config.json back and restarted and recompiled all plugins. After that pimatic worked again.
I found out that the issue was related with the available diskspace. Some log file filed up the complete space and thing started to ruin the stability.

**Comment by sweetpi** [comment]
@htca Good to hear. Since some minor updates pimatic has log rotation and deletes old log files automaticly.

**Comment by neographikal** [comment]
I think the elves in the magical forest did a sun dance and helped me, problem has been solved while I did nothing at all. I like that, should happen more often...

**Comment by HansKappert** [comment]
I had the same problem. It was caused by the fact that a small part was missing from the config.json under de plugin section:
{
"plugin": "mobile-frontend"
},

I had already tried to re-install everything, but after that I copied my backed up config into the piratic-app folder, causing the same issue again. When I used the default config.json the interface was there again. Go figure :-)
