### ISSUE TITLE
electric candles

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#490]
I found electric candles with a remote control on the internet. Wouldn't it be cool to control them with pimatic? Never seen this before, but theoretically it should work? How big is the change they are 433Mhz?

![nqutnm1397202200111](https://cloud.githubusercontent.com/assets/10496485/5802749/287e1642-9ff8-11e4-8da5-17165ed93719.jpg)
![x4-life-led-kaarsen-met](https://cloud.githubusercontent.com/assets/10496485/5802750/289bc098-9ff8-11e4-80ba-2865d5dd3b80.jpg)

**Comment by Oitzu** [comment]
The remote looks like a Infrared remote to me.

**Comment by leader21** [comment]
> like a Infrared remote to me.

wouldn't say so. having an rf remote with a similar design.
i saw the candles from the second picture at the website of the german vendor "Voelkner"
http://www.voelkner.de/products/540935/X4-Life-3er-Set-Led-Echtwachskerzen.html
just sent an email with the question if ir or rf remote and frequency. let's see if they can help.
otherwise a datasheet from the manufaturer would be very helpfull if there is some (since i guess it's china made, could be hard to get ^^)

**Comment by sweetpi** [comment]
I think its infrared. If it would be 433mhz it would be labeled as it.

**Comment by leader21** [comment]
yes, i guess you are right Oliver. seems to be IR.
i found a similar product at amazon which is controlled via IR remote.
http://www.amazon.de/dp/B00IJM6SYI?psc=1

**Comment by sweebee** [comment]
The manual says: max distance from remote 4 meters, so must me ir.

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
