### ISSUE TITLE
Communication in the pimatic community

### ISSUE THREAD

**Issue by Oitzu** [pimatic/pimatic#495]
Is there some sort of irc-channel or similar to communicate directly with the pimatic community?
Would be nice to have some place to exchange ideas/experiences etc..

**Comment by leader21** [comment]
not yet. also there's no forum or anything like that.

maybe a forum could be useful in future since the same questions (especially for pimatic newbies) will come up again and again. maybe a forum will reduce the amount of issues here at git and would help to stay clearly arranged at git for having only the important projects for developing.
a forum is known and accepted by many people. git is very special for developers and advanced users. i would also say that some people don't dare to post their issues here. a forum is more familiar, if you know what i mean ;)

there surely will be some people to moderate this forum if there would be one (me included, having some experiences ;)
but as i said - this is up to sweetpi to decide. he will have his reasons why there's no forum.

**Comment by Oitzu** [comment]
I don't know if he has his reasons why there's no forum or if he just does not see any demand for having one. But yes, it is up to sweetpi to decide stuff like this.
Would even be nice to know each other a little better and to discuss some stuff that don't deserve an own issue. 
And would be nice to connect to some people nearby that try to archive the same or similar.
I already know, from one of your screenshot from a other issue, that you seem to live anywhere near Dillenburg. Greetings from Biedenkopf neighbour. ;)

**Comment by leader21** [comment]
> Greetings from Biedenkopf neighbour. ;)

hey!! nice to hear!! it's a small world ^^

**Comment by Oitzu** [comment]
For example it would be nice to know which equipment German users are using and where to get it.
I'm fairly new to this topic and only controlling 4 sockets and reading one self-build temperatur sensor with pimatic.
At the moment i'm trying to figuring out at which point i should invest my time and money to expand this.
There would be 3 points i'm interested to control with pimatic:
1) My radiators (I have no clue whats the best to buy to do this)
2) A fan in the basement that needs to be powered on based on humidity (i'm thinking about using a dht11 to measure humidity and powering it on/off with an wallsocket)
3) Lights in different rooms (I've seen some cheap rf switches at pollin but first i need to check the cabling in my apartment)

**Comment by leader21** [comment]
pimatic is very powerful! there are so many possibilities to use it.
but to answer your questions from my point of view
1) go for the max! thermostats and cube. i'm having 4 thermostats installed. they are working without any problems. it's not that expensive, compared with other products that do the same for more money. pimatic can operate the thermostats via plugin. have a look at www.elv.de there you can buy the components as ARR kit (almost ready to run, some kind of advanced DIY). Some cheaper and not that hard to assemble.
2)if your RF signal will make it through to the basement then you could use a RF weather sensor for temp and humidity. An Intertechno switch like ITL1000 can be used for switching the fan.
if the RF signal is not that strong, maybe a second pi with pimatic in the basement with an dht22 sensor directly attached to gpio for the humidity and a relais attached to gpio for the fan could do the job.
3)depends what you want to do - plug sockets like Intertechno IT1500 or like the wired devices ITL1000 or dimmer like ITL300 etc. There are so many devices for almost every possible usage. Personally I prefer Intertechno or Duewi devices.

**Comment by sweebee** [comment]
I think a forum would be great.

Sharing your setups.
Tutorials setting up devices and rules.
Sharing creative combinations of hardware/software.
Brainstorming about new possibilities.

**Comment by Icesory** [comment]
I think we need more core programmer first. I have little bit experience with programming but I am not able to code in the core (framework). 
To administrate a forum is a lot of work. 
I can create the place for a forum on my root server. So this can run without of costs. But this is a new big project. And sweetpi makes this all in his free time.

**Comment by leader21** [comment]
> To administrate a forum is a lot of work.

yes, but maybe it's worth a try. sure it's lots of work. coding is lots of work too. and i could imagine that there are people who want to contribute but cannot code (like me ^^) 
imho the most work is to set up the whole thing. once it's running, there will be administration and moderation done by a team of people. and i think that the in the beginning the forum would be used to discuss the "core" themes. but if these were fully discussed, there won't be so much new discussions imho. 
but i can imagine that there are special questions as here on git that only Oliver is able to answer. and maybe it's just too much to handle anyways. 

> I think we need more core programmer first.

yes of course! but since pimatic is growing fast it's "community" will grow fast too (just have a look at the amount of issues that have been created the past weeks).
but you are totally right, there should be more coder since Oliver cannot do all the work himself and some projects are certainly very demanding. 

i can imagine that core coding assumes good programming skills and lots of time.
but as it's always with free projects - everybody contributes as good as he's able and wants to.
you cannot force development but you can inspire. the more inspiration, the more contributors. and maybe there will be some good coders amongst, who nows. 

anyway, pimatic is great, with or without forum. thanks to Oliver for that fine piece of software and everyday a little more inspiration ;)

**Comment by sweetpi** [comment]
There are two main reasons, why there is no forum:

1) Maintaining a forum leads to more tasks beside development (updating forum, spam prevention, moderating, backups,...) and I wanted to keep my focus on the development of pimatic. 
2) github issues are very well integrated with git and its easy to reference from patches to github issues and vice versa, what I think is a big advantage over a plain forum. With and additional forum we would split discussions into two places.

However. I think its worse a try. In particular because the issue section trends to get unmanageable and unclear, because there is no real categorization. I found a modern forum software with some plugins for github integration: https://community.nodebb.org/

I will give it some tests.

**Comment by koffienl** [comment]
For Dutch users : http://gathering.tweakers.net/forum/list_messages/1609839

**Comment by Oitzu** [comment]
Well, the work of maintaining a forum was the reason i mentioned a irc-channel or similiar first (I'm not sure whats the preferred way to communicate directly in tech-groups nowadays).
Would give a simple direct way to communicate with each other without the need of much maintaining.
It should not be the basis of helping everyday users to solve their problems or bugs but to communicate more directly to each other interested in extending or improving pimatic.

**Comment by sweetpi** [comment]
Let's give it a test for a week and then decide further: http://forum.pimatic.org/
You should be able to login with a github or google account or just create a forum account.

If someone want to moderate the forum send me a pm or mail.

**Comment by leader21** [comment]
Thanks a lot for this approach!! 
let's see what happens!

**Comment by ituri** [comment]
> there's also a chat

Where?

**Comment by leader21** [comment]
check here 
![chat](https://cloud.githubusercontent.com/assets/8620305/5889195/a4bba6b2-a41b-11e4-9168-1d7681dad5c3.jpg)
but unfortunately no group chat :/

**Comment by ituri** [comment]
What about IRC? I guess that most of the people who are into open source software are on freenode every once in a while.
I've opened up [#pimatic](irc://irc.freenode.net/pimatic) - let's see if we can manage to get some pimatic users and developers in there.

**Comment by koffienl** [comment]
I haven't been on IRC since at least 10 years :)

**Comment by leader21** [comment]
> Let's give it a test for a week and then decide further

well, in my opinion the forum is effective.

**Comment by Yves911** [comment]
should we all move to the forum now and use git only for dev things?
Currently we have two different places for info that's not the best option.

**Comment by leader21** [comment]
> should we all move to the forum now and use git only for dev things

guess this would be better. i think this will be that way in the near future. 
at the moment there are still open questions here at git. in my opinion the better way would be to use the forum for communication and coordination and only to open issues on git for dev or bug purposes as you mentioned above. 
this should give the developers the possibility to keep an eye on their projects here. 
the forum is not known to everybody since it's only a week old. give it some time to get used to the innovation. don't know if there's a possibility to issue a mail to all participants of the pimatic project here on git. could be an option to inform all users at once.

**Comment by sweetpi** [comment]
Yes I think that's the way to go, too. I want to have the issue section just for developer questions or bug reports. All other discussions including helping user, guides and troubleshootings should go into the forum.

I will promote the forum soon more offensive.

**Comment by sweetpi** [comment]
So think we keep the forum, added a contribution guideline to github, what makes clear, what to ask where and promote the forum more offensive in the readme.

**Comment by Oitzu** [comment]
I'm making a note here: HUGE SUCCESS.

**Comment by sweetpi** [comment]
I like it indeed, too :)
