### ISSUE TITLE
Problems after update 0.8.4 guess its homeduino ..

### ISSUE THREAD

**Issue by leader21** [pimatic/pimatic#518]
After the latest update to pimatic 0.8.4 my Pimatic has serious trouble.
I updated to 0.8.4, after the restart, my Pimatic doesn't work as usual anymore.

The problem is that it doesn't start. 
I already set the debug mode but that's the only thing I get actually.

![](http://www.youscreen.de/powdutbn49.jpg)

any idea or suggestion what that could be? 
FYI I'm using the RFControl from Icesory's dev branch (if this does matter)

when i remove the homeduino plugin from the config, pimatic starts without issues.

**Comment by leader21** [comment]
mmmmh ... did a apt-get update and upgrade and updated the firmware of the pi and now it seems to work again. 
maybe i've had some older libraries.
i'll close this issue, since Pimatic seems to be working now.

**Comment by Yves911** [comment]
Look similar to the issue i have also : https://github.com/pimatic/pimatic/issues/443
and that i reported here too http://forum.pimatic.org/topic/44/database-configuration-howto/13#
I have updated my pi to last version of everything and the firmware also but still have those errors...

**Comment by leader21** [comment]
ah ok i see - i am also using a new database. 
maybe the old database got pimatic stuck ...

**Comment by sweetpi** [comment]
I don't think that apt-get update or firmware update is useful here. 

@leader21 The error in you log is most probably the bug in the node-serialport lib that I fixed recently, but didn't create a pull request, yet (https://github.com/sweetpi/node-serialport/commit/e013d1ed6c9dc2d248c5657f6c4c6e0f4e80becc)

The strange thing is that this code is only executed when the serialport connection is paused or gets disconnected. But its never paused by pimatic, so it seems that its actual the same problem like @Yves911 has, that the serialport gets disconnected.

I've the impression that the deleting expired attributed action blocks the whole node.js process and so somehow the serial connection gets disconnected. Maybe I'm not running in this issue on the banana pi, because it has two cores. Could one of you send me his big database? Then I setup some test system on an rpi and hopefully trace this down.

**Comment by leader21** [comment]
sorry, i deleted my old database :(

**Comment by Yves911** [comment]
@sweetpi i am sending by email you a link to download my DB from Dropbox

**Comment by sweetpi** [comment]
I hope to find time at the WE to fix this. Its not easy to debug.
