### ISSUE TITLE
How to switch on debugging for homeduino

### ISSUE THREAD

**Issue by AvdH** [pimatic/pimatic#562]
I want to scan the codes send by my remote switches. I read some docs about enabling the debugging of the homeduino. that would reveil the code send by the remote / received by homeduino.
How can i enable this logging, and where can i find the log entries?

**Comment by sebastienvg** [comment]
If your RF devices are properly hooked up and you've added the homeduino to your config.json then you should see RF debug info in the "messages" in the pimatic UI.

Another way is to go to your homeduino folder and run ```make monitor``` once the screen session open you have to type

``` RF receive 0``` when you type nothing happens on the screen but you'll get ```ACK``` once you press return. From there you can just push the buttons on your remote on you should see things in the screen session.

Hope this helps!

**Comment by Heizelmann** [comment]
Also see http://forum.pimatic.org/topic/73/solved-how-to-disable-debug-logging-for-homeduino/3.
Ther is a new config property 'debug'.

**Comment by sweetpi** [comment]
But it should be on by default.

**Comment by AvdH** [comment]
if I use the monitor (with make monitor) i receive the data from the Arduino, but it doesn't tell me what protocol systemcode / progrmcode etc) I believe this is done in the plugin. I don't get anything in the messages in the UI.
I do have the receive on pin 1 and not on pin 0. Maybe that is the problem. As I have  everything still on a breadboard I will rewire it to use pin 0 and try again tomorrow.
Thanks for the quick response.

**Comment by AvdH** [comment]
Found it, I changed the setup on the breadboard. It is now using the default pins.
      "receivePin": 0,
      "transmitPin": 4,
      "debug": true

**Comment by Icesory** [comment]
You can define the pins in the Config. Normally pin 0 and 1 should work for receiving

**Comment by AvdH** [comment]
@Icesory I did change the config. It was originally "receivePin": 1 and "transmitPin": 10. But receiving didn't work. Transmit did. After changing the receive Pin to 1 on the breadboard and the config the receiving worked ok.

**Comment by Icesory** [comment]
The receive PIN number isn't the pin number on the arduino. It is the number of the external interupt.

**Comment by Yves911** [comment]
@sweetpi 
```
But it should be on by default.
```
Yes it is.
For those that see no message coming pls update your pimatic config and add
```
    "logLevel": "debug",
```
right after  "locale": "en"
The you will see messages coming from homeduino

**Comment by macpit** [comment]
Hi all,

I have the same problem, no login messages:
----------------
pi@raspberrypi ~/pimatic-app/pimatic-app $ sudo node_modules/pimatic/pimatic.js
10:44:28.148 2015-04-12 Sunday
10:44:48.415 [pimatic] Starting pimatic version 0.8.66
10:44:53.002 [pimatic] Loading plugin: "pimatic-homeduino" (0.8.50)
10:44:58.150 [pimatic] Loading plugin: "pimatic-shell-execute" (0.8.10)
10:44:58.332 [pimatic] Loading plugin: "pimatic-cron" (0.8.5)
10:45:00.581 [pimatic] Loading plugin: "pimatic-mobile-frontend" (0.8.61)
10:45:05.271 [pimatic-cron] the time is: Sun Apr 12 2015 10:45:05 GMT+0200 (CEST)
10:45:05.657 [pimatic] New device "Weather Data"...
10:45:05.811 [pimatic] New device "Weather Data 2"...
10:45:06.163 [pimatic-homeduino] Connected to homeduino device.
10:45:06.966 [pimatic-mobile-frontend] packing static assets
10:45:09.177 [pimatic-mobile-frontend] packing static assets finished
10:45:09.217 [pimatic-mobile-frontend] rendering html
10:45:32.094 [pimatic-mobile-frontend] rendering html finished
10:45:32.248 [pimatic] Listening for HTTP-request on port 8080...
----------------
Config :

pi@raspberrypi ~/pimatic-app/pimatic-app $ cat config.json 
{
  "//": "Please only change this file when pimatic is NOT running, otherwise pimatic will overwrite your changes.",
  "settings": {
    "httpServer": {
      "enabled": true,
      "port": 8080,
      "debug": true,
      "locale": "en",
      "logLevel": "debug"
    },
    "database": {
      "deviceAttributeLogging": [
        {
          "deviceId": "*",
          "attributeName": "*",
          "type": "*",
          "interval": "0",
          "expire": "7d"
        },
        {
          "deviceId": "*",
          "attributeName": "*",
          "type": "continuous",
          "interval": "5min",
          "expire": "7d"
        },
        {
          "deviceId": "*",
          "attributeName": "temperature",
          "type": "number",
          "expire": "1y"
        },
        {
          "deviceId": "*",
          "attributeName": "humidity",
          "type": "number",
          "expire": "1y"
        }
      ],
      "messageLogging": [
        {
          "level": "*",
          "tags": [],
          "expire": "7d"
        },
        {
          "level": "debug",
          "tags": [],
          "expire": "0"
        }
      ]
    },
    "authentication": {
      "secret": "DnjCp5lEtrzV7gQoerqfL3exq7qCXu3l88xZ8qcV+65zMB8HrTJijCF62FVShJz+cRIJvjioxkFwODlqbZwjVw=="
    },
    "httpsServer": {},
    "gui": {}
  },
  "plugins": [
    {
      "plugin": "homeduino",
      "driver": "gpio",
      "driverOptions": {},
      "receiverPin": 1,
      "debug": true,
      "logLevel": "debug",
      "transmitterPin": 0
    },
    {
      "plugin": "shell-execute"
    },
    {
      "plugin": "cron"
    },
    {
      "plugin": "mobile-frontend"
    }
  ],
  "devices": [
    {
      "id": "weatherstation",
      "name": "Weather Data",
      "class": "HomeduinoRFWeatherStation",
      "protocols": [
        {
          "name": "weather5",
          "options": {
            "id": 36
          }
        }
      ],
      "values": [
        "temperature",
        "humidity"
      ]
    },
    {
      "id": "weatherstation2",
      "name": "Weather Data 2",
      "class": "HomeduinoRFWeatherStation",
      "protocols": [
        {
          "name": "weather5",
          "options": {
            "id": 586
          }
        }
      ],
      "values": [
        "temperature",
        "humidity"
      ]
    }
  ],
  "rules": [],
  "pages": [
    {
      "id": "weather",
      "name": "Weather",
      "devices": [
        {
          "deviceId": "weatherstation"
        },
        {
          "deviceId": "weatherstation2"
        }
      ]
    }
  ],
  "groups": [],
  "users": [
    {
      "username": "admin",
      "password": "admin",
      "role": "admin"
    }
  ],
  "roles": [
    {
      "name": "admin",
      "permissions": {
        "pages": "write",
        "rules": "write",
        "variables": "write",
        "messages": "write",
        "events": "write",
        "devices": "write",
        "groups": "write",
        "plugins": "write",
        "updates": "write",
        "database": "write",
        "config": "write",
        "controlDevices": true,
        "restart": true
      }
    }
  ],
  "variables": []
}pi@raspberrypi ~/pimatic-app/pimatic-app $
