### ISSUE TITLE
[pimatic-gpio]: Error loading device x: EIO, i/o error

### ISSUE THREAD

**Issue by p4co86** [pimatic/pimatic#588]
got the following issue its closed yesterday here on github.
pimatic and plugins are up to date, is use a raspberry 2
```
[pimatic]: Error loading device z: EIO, i/o error
[pimatic]: Error loading device y: EIO, i/o error
[pimatic]: Error loading device x: EIO, i/o error
```

**Comment by sweetpi** [comment]
Did you try reverting the firmware https://github.com/pimatic/pimatic/issues/548#issuecomment-75368750 ?

**Comment by p4co86** [comment]
Yes. Mo success

**Comment by sweetpi** [comment]
It happens only on startup, or?

I think we have to wait till its fixed in the kernel, as a work around you could add a sleep before starting pimatic ins the startup-script.

**Comment by p4co86** [comment]
Ok. Thank you

**Comment by fivdi** [comment]
I think this issue is related to https://github.com/fivdi/onoff/issues/31

**Comment by mrdago** [comment]
I'm seeking desperately on a workaround for the gpio i/o error at boottime.

At which place the sleep has to be placed and what is the right sleep value?
Are there other known and tested workarounds?

Thanks in advance!

**Comment by fivdi** [comment]
I don't actually use pimatic, but if I'm not mistaken this issue is related to functionality that was removed from the Linux kernel that will not be replaced. Old Linux kernels can detect interrupts on GPIO output pins (YES OUTPUT PINS), but new Linux kernels can't. pimatic-gpio still relies on this old functionality [here](https://github.com/pimatic/pimatic-gpio/blob/master/gpio.coffee#L40). Here, a GPIO output is being configured as an interrupt generating output, but this is no longer supported, and results in errors at runtime.

As already stated, I haven't used pimatic, so may be completely incorrect.

@mrdago is your code using the [GpioSwitch](https://github.com/pimatic/pimatic-gpio/blob/master/gpio.coffee#L35-L60) class which contains the offending code?

**Comment by sweetpi** [comment]
@fivdi Thanks for pointing this out. I think you are right. Removed the problematic code. @p4co86 Could you test with pimatic-gpio version 0.8.5?

**Comment by mrdago** [comment]
@sweetpi  Issue solved!

I just upgraded to pimatic-gpio version 0.8.5 and after reboot the gpio outputs to my 8 relay module are initialized without any error. dmesg no longer shows I/O errors.

Thank you for fixing that!
