### ISSUE TITLE
[pimatic] Plugin update fails silently

### ISSUE THREAD

**Issue by mwittig** [pimatic/pimatic#663]
Pimatic does not appear to install the plugin package updates. After restarting the same package are listed again for update. Installation of the updates from the command line works as expected.
....
pimatic is up to date.
Found update for pimatic-edimax: current version is 0.0.9, latest version is: 0.1.0
Found update for pimatic-solarview: current version is 0.0.8, latest version is: 0.0.9
....
npm http GET https://registry.npmjs.org/pimatic-edimax
npm http GET https://registry.npmjs.org/pimatic-solarview
Die Aktualisierung war erfolgreich. Bitte Pimatic neu starten.
.....
18:40:39.460 [pimatic] info: Installing: "pimatic-edimax" from npm-registry.
18:40:41.591 [pimatic, npm] info: http GET https://registry.npmjs.org/pimatic-edimax
18:40:45.855 [pimatic] info: Installing: "pimatic-solarview" from npm-registry.
18:40:48.203 [pimatic, npm] info: http GET https://registry.npmjs.org/pimatic-solarview
19:03:34.799 [pimatic] info: Restarting...
19:03:34.811 [pimatic] info: Flushing database to disk, please wait...
19:03:35.025 [pimatic] info: Flushing database to disk, please wait... Done.
19:03:37.237 2015-05-29 Friday
19:03:43.988 [pimatic] info: Starting pimatic version 0.8.70

**Comment by sweetpi** [comment]
What's your npm version?

**Comment by mwittig** [comment]
npm -version
1.4.28

**Comment by sweetpi** [comment]
Could you test with npm 2 (`sudo npm install -g npm`)?

**Comment by mwittig** [comment]
OK, will do. 

Regarding version 1.4.28 this appears to be a intermittent problem.

**Comment by mwittig** [comment]
The same problem has occurred again, now using npm 2.11.0! Two updates (pimatic and pimatic-probe) worked fine. The third one (pimatic-openweather) failed. Trying this again and again it suddenly worked. Is this somehow related to the status of https://github.com/pimatic-ci/pimatic-openweather/releases? I have just noticed the new release was filed just 7 minutes ago. So there is gap netween the new version published and the release filed on pimatic-ci

```
Found update for pimatic-openweather: current version is 0.8.9, latest version is: 0.8.10

npm http GET https://registry.npmjs.org/pimatic-openweather
```

**Comment by sweetpi** [comment]
The Updater has two methods for installing plugins. The first is through npm (using `npm install`) and the second is by downloading a precompiled binary from github.

The second works much better for the raspberry pi, because the tar.gz release archive contains all binaries and dependencies and so the install process is much faster then with npm. The release archives are created using travis (https://travis-ci.org/sweetpi/node-module-compiler) and currently only for arm. The installer picks the second method when ever there is a release packages for the current version available. Since it needs some time to build them, there is the mentioned gap between npm publish and travis build, where the installer falls back to npm install (and not all packages can be precompiled on travis, because of dependencies to special libs).

 I hope to find some time to debug why npm fails.

**Comment by mwittig** [comment]
Thank you for the clarification.

**Comment by mwittig** [comment]
Seems to fixed now
