### ISSUE TITLE
Update bluebird and lodash dependencies

### ISSUE THREAD

**Issue by mwittig** [pimatic/pimatic#758]
The versions used in pimatic are pretty much outdated. For lodash you will even get deprecation warnings. I am using these packages as part of plugins via env. 

In particular I am missing the following features:
- bluebird mapSeries(). Not supported in earlier versions
- lodash has() and get() supporting access via path. Earlier version only support access by key.

**Comment by sweetpi** [comment]
Your are right, these dependencies are outdated. 

However I normally don't want to update to a higher major version of a dependency without updating the major version of pimatic, because of breaking api changes. 

I **think** its pretty save for lodash 2.4.1 to 3. and bluebird  2.10 to 3, but I have to do some testing. Did you do some tests already?

**Comment by mwittig** [comment]
I haven't tested it thoroughly, yet. 
Let me do more testing at my end and I'll issue a PR if successful.

**Comment by mwittig** [comment]
This still requires some action from my side. It would be nice to move to lodash 4, but unfortunately some deprecated functions have been removed - mostly renamed functions

**Comment by mwittig** [comment]
I am closing this now, but I think we need to revisted the matter for future versions. Keeping the stuff more or less up-to-date is always an issue
