### ISSUE TITLE
Install pimatic with existing sqlite instance

### ISSUE THREAD

**Issue by ChupZz** [pimatic/pimatic#781]
Hi there, 
I've got a little of a Problem with installing Pimatic while my Pi is running an Owncloud. 
I think the Problem is that my Owncloud is using sqlite3 as well. 
From my Owncloud config.php 
 'dbtype' => 'sqlite3',
  'version' => '8.2.2.2',
Pimatic keeps haning stating this line: (for 2 hrs. right now)
01:26:36.424 [pimatic] Listening for HTTP-request on port 5000...

Is there any possibility I can install Owncloud and Pimatic simultaneous?
Also there is running a lighttpd - but I added a listener for my Port (5000). Could this also be a Problem?
This is my config.json: 
 "settings": {
    "httpServer": {
      "enabled": true,
      "port": 5000
EDIT: 
 sudo netstat -tulpen |grep 5000
tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      0          26471       3037/node

I would appreciate an answer. 
Sorry for the bad grammar and language. 

If you need further Information just let me know

Best Regards, 

ChupZz

**Comment by Icesory** [comment]
Because this isn't really a bug, can you please ask your question in our forum. 
forum.pimatic.org 
You can login with your github.com account. 

This line
01:26:36.424 [pimatic] Listening for HTTP-request on port 5000...
Is a normal message from pimatic and says you that it is waiting for an user. 
Have you tried to open the pimatic Web page?

**Comment by sweetpi** [comment]
Seems like normal behavior. There should be no problem with owncloud using sqlite, because pimatic uses its completely separated own sqlite module. Check if you can access the webfrontend through port 5000.
