### ISSUE TITLE
Presenting a new repo

### ISSUE THREAD

**Issue by roccomuso** [pimatic/pimatic#797]
Hi guys,

I just wanna show you my new repo, inspired by pimatic.. There's something in common but also really different implementations and features..

https://github.com/roccomuso/iot-433mhz

Any feedback would be appreciated. Thanks!

**Comment by Icesory** [comment]
Really interesting. 
I like the UI a lot. 

But Pimatic is a lot more than an 433MHz controller. There are dozens of plugins available for all kind of stuff. Johnny-Five, MySensors, Dht and many more. Different native Android apps are also in development. 

What didn't you like on pimatic? What are your reasons to create a own system? 
It would be awesome to get your UI for pimatic as an own plugin.

**Comment by sweebee** [comment]
The funny thing is that I'm reducing the amount of 433mhz devices. The reason I chose for pimatic is because of the combinations of protocols. I'm only using 433mhz for wall remotes. All the lights are now hue or mysensors. All my pirs and light sensors are also mysensors

**Comment by mwittig** [comment]
Rocco, thanks for sharing your project with us! I really like the UI snapshot and I'll definately trial your project. As @Icesory said one of the strengths of pimatic is providing a large base of plugin and it also has various frontends to offer. In line with what @sweebee said I think 433 Mhz device provide for first entry to the world of home automation because they are cheap and simple and you probably already have them home. However, after a while a lot of users reaslize the advantages other technologies have to offer in terms of reliabilty and security or they simply want to quality products integrated like the hue lights for example. So, I am curious to better understand the rationale behind your project.

One question about installation. Wouldn't it be good enough to install the package with a non-privileged user? This way one can easily circumvent the permission issues. Generally, npm install as root is not recommended unless it is global install, i.e, for a command wrapper like gulp or grunt.

**Comment by roccomuso** [comment]
Thanks for you replies :)

@Icesory Well this was a thesis project. I had a lot of 433mhz in my home, so I've decided to build something cool, easy to interact and start with. The system is pretty intuitive. The are a lot of cool features. You can have the UI open on several devices and it will be updated in real time. On mobile you can shake your smartphone and automatically the cards reorganize himself on every UI. Thanks to the API also for this system is really easy to build any kind of plug-in or mobile native interfaces.

@sweebee Yeah I use 433mhz for wall remotes, pir and door sensors. But also light can be turned on with 433mhz. Philips Hue are great of course, but really expensive don't you think?

@mwittig I'm glad you guys liked the UI :) 433mhz are well-spread on the market and so really cheap. Actually I didn't find for instance, cheap wifi PIR sensor.. or cheap wifi wall socket. If you guys wanna show me something, more than happy to see it :) 
As regards the installation, this is a package globally installed. And some dependencies (especially node-serialport) requires root privilege I guess and the <code>--unsafe-perm</code> flag too. Don't know how to "fix" that yet.

Of coure you're right, pimatic got a lot of plug-in and more flexibility. :) I just think my naive project got a "easy to use" approach.

**Comment by mwittig** [comment]
Rocco, thanks for your feedback. I agree with what your're saying regarding wifi sensors and such. Either a specifc product (e.g. Wifi PIR) is not available or the stuff is expensive, no matter whether ut is Wifi, ZigBee , zWave or whatever. The average cost per data point (sensor/actuator) is at about 35-50 Euros while 433 Mhz stuff is available for a few Euros. This is why some fo use started tinkering with ESP-8266 which gives you a platform to roll your own Wifi-Sensors. See http://forum.pimatic.org/topic/1225/espimatic-esp8266-modular-sensor-for-pimatic-update-released for example.

Hopefully, your thesis was great success for your career and you find the time/opportunity to continue work on your project. You are also very welcome to contribute to Pimatic.

**Comment by sweebee** [comment]
I think hue is not that expensive. White hue bulbs are 17 euro's And dimmable (And 100x more reliable) look at the price of 433mhz dimmers. Z-wave dimmers are around 50-60 euro. For that you have a rgbw hue bulb.

**Comment by mwittig** [comment]
May Hue is cheaper in NL than in Germany?! In Germany, a hue starter set with 3 RGB bulbs costs about 175 EUR - well, Media Markt had an offer with 2 Lux white bulbs for 80 Euros. Compared to this Milight is less than half of the price. However, I like hue for color rendition which is way better than Milight.

**Comment by sweebee** [comment]
Hue color is around 53 euro's. 
Hue white around 17 euro's. 
You'll still need a bridge ofcourse, but you only need 1.

**Comment by roccomuso** [comment]
@mwittig yeah i'm using esp8266 too and waiting for the new ESP32. I worked a lot with MQTT protocol and esp8266-based sensors... anyway thanks :)

@sweebee Here in italy a white bulb 20 euros. And 80 euros 2 white bulbs and a Bridge.
PS. also the Milight needs a Bridge am i right?

**Comment by mwittig** [comment]
> PS. also the Milight needs a Bridge am i right?

Yes, the Wifi bridge costs about 20 EUR and 6W RGBWW bulb is about 13 EUR. It is also possible to build your own bridge - https://github.com/henryk/openmili

**Comment by sweetpi** [comment]
@roccomuso Nice project and thanks for posting here.

The gui concept is very interesting and looks very nice. I would have loved to see it as a alternative pimatic gui plugin (like the [pimatic-angular-material-frontend](https://github.com/denniss17/pimatic-angular-material-frontend)). 

I have seen you have choosen RCSwitch as 433mhz solution. I think the homeduino approach is much more advanced and powerfull. So if you contine with the project maybe consider using my [homeduinojs](https://github.com/pimatic/homeduinojs) library. Would be nice to see some adoption outside of pimatic.

I mark this issue as closed because its not really pimatic related and such things are better discussed at the forum.
