### ISSUE TITLE
Adding attributes on the fly in Custom Device?

### ISSUE THREAD

**Issue by hongkongkiwi** [pimatic/pimatic#928]
Small question for the developers if you have a moment.

I'm writing my own Device and I would like to add some attributes on the fly. Essentially I'm doinga  request to a webserver and based on the results I will dynamically add some attributes.

I can't seem to find any way to add attributes except from the class constructor, is there any other way? Ideally I would like to add them in another method

**Comment by mwittig** [comment]
You can only dynamically add attributes to the device at construction time (as part of the device constructor before super() is being invoked). There are a few examples for this. See https://github.com/mwittig/pimatic-fronius-solar/blob/master/fronius-solar.coffee#L307 for example. Don't get confused by the `attributeTemplates` declaration. It is simply an object of schema definitions for attributes I use to dynamically create attributes which the user has configured to be included in the device.

**Comment by sweetpi** [comment]
@mwittig is right. Generally you can't add attributes after device construction.

However what you can do with v0.9 is recreating the device on the fly. So you can:

1. Create the device without any attributes
2. Mage the request to find the attributes to add.
3. Call `@framework.deviceManager.recreateDevice(oldDevice, newDeviceConfig)`.

However you should cache the attributes in the device config (at step 2). So that the device is created with attributes on restart. If you would always create the device without attributes first, then for example rules that depend on the attributes of the device would fail first and throw errors on startup.

**Comment by hongkongkiwi** [comment]
@mwittig - Thanks for the example! I will study this, very helpful.
@sweetpi  - That's a very good idea, do you know how I would initiate a callback to the Plugin class from the Device class to tell the Plugin class to initiate the reload.

Just to give a slight bit of background, I'm working on an Uber plugin which has different "products" in each country. So although users could hard-code the products, it would be easier if I can just automatically load them, or as suggested I will do an HTTP request, get the products, cache them then reload the plugin.

**Comment by mwittig** [comment]
> That's a very good idea, do you know how I would initiate a callback to the Plugin class from the Device class to tell the Plugin class to initiate the reload.

Either 1) make a plugin variable visible to the device with the module space, **or** 2) pass the plugin instance to the device via the device constructor:

1) 
```
# Simply define a plugin variable (usually at the bottom of the file) before the device classes 
myPlugin =  new DenonAvrPlugin

class MyDevice extends env.devices.Device
...
  
## at the end of file
return myPlugin
```

2) 

```
     ...
     # plugin device initializer
     @framework.deviceManager.registerDeviceClass("SensiboDevice", {
        configDef: deviceConfigDef.SensiboDevice,
        createCallback: (config, lastState) =>
          # 2nd paramter is this (the plugin instance) 
          return new SensiboDevice config, @, lastState
      })
     ....

  class SensiboDevice extends env.devices.PowerSwitch
    constructor: (@config, @plugin, @service) ->
    ...
```

**Comment by mwittig** [comment]
Your work on an Uber plugin sounds exciting. Looking forward to your contribution!

**Comment by thexperiments** [comment]
I also faced the same "problem" with my new plugin for the harmony hub. I decided that the easiest way to handle this for now is to break down a device with many functionalities into subdevices and add a good auto discovery.

Now you for example get a ButtonsDevice for all play/pause skip etc via autodiscovery. If you only need the play/pause you can delete the other buttons because you can very quickly use the discovery to add the device with the full functionality again.
