### ISSUE TITLE
[0.9] Default values not populating on plugin

### ISSUE THREAD

**Issue by hongkongkiwi** [pimatic/pimatic#934]
It seems that on the latest version of Pimatic (0.9.2.5), default values for the plugin are not populating in the @config variable.

In my plugin code:

```coffeescript
  class TTSPlugin extends env.plugins.Plugin
    init: (app, @framework, @config) =>
      console.log @config
```

In my plugin-config-schema.coffee

```coffeescript
module.exports = {
  title: "TTS Plugin Config Options"
  type: "object"
  properties:
    blah:
      description: "Testing"
      type: "string"
      default: "hi"
}
```

Gives me:
```json
{ 
  "plugin": "tts",
}
```

However I expected:
```json
{ 
  "plugin": "tts", 
  "blah": "hi"
}
```

The results are simply whatever is in the config.json, it doesn't automatically fill in the fields with defaults which is what I expected. Is this a bug or am I doing it wrong?

**Comment by mwittig** [comment]
Yes, the default values for plugins need to be handled manually. The following has worked for me
```
intervalSeconds = @plugin.config.interval ? @plugin.config.__proto__.interval)
```
for the following property definition
```
interval:
      description: "Polling interval for switch state in seconds"
      type: "number"
      default: 60
```

You may be add defaults as a whole, e.g. using lodash's _.defaults or _.defaultsDeeep methods, but I haven't tried that.

**Comment by sweetpi** [comment]
The default values should be populated in the prototype chain. @mwittig There should be no need of accessing the `__proto__` property or using lodash.

The default values are added to the protoype chain, therefore these are not printed in console.log, however

```
console.log @config.blah
```

should print "hi"

We don't add the property to the config object directly, because the default values should not be saved to the config file.

Simplified of what we are doing:

```
var config = {} // config from config.json
var defaults = {blah: 'hi'} // defaults from config schema
config.__proto__ = defaults //populate prototype chain with defaults

console.log(config) // gives {}
console.log(config.blah) // gives 'hi'
```

In summery the value is not printed, if you print the config object. However it can be directly access by `config.blah`.
