### ISSUE TITLE
npm pimatic dht-sensor

### ISSUE THREAD

**Issue by kregory** [pimatic/pimatic#948]
Hello,

sometimes readen value are totally absurde, like -3267°C and 6653%.

pimatic V0.8.107
npm V1.3.21
pimatic-dht-sensors V0.8.6

**Comment by mwittig** [comment]
I think it is an issue with read timings used by underlying base package.  These issues should have been fixed with the new plugin version for pimatic 0.9. Unfortunately, the new plugin version is not compatible with the node version used for pimatic 0.8. Please consider upgrading to pimatic 0.9 as there are no plans to further maintain v0.8 plugins. More information about migrating to pimatic 0.9 can be found on the pimatic forum. 
* https://forum.pimatic.org/topic/1903/announcing-the-release-of-pimatic-v0-9
* https://forum.pimatic.org/category/31/pimatic-v0-9

**Comment by kregory** [comment]
Hi 

I've upgraded pimatic, all was fine since today.
The sensor has recorded bad value this morning ...

**Comment by mwittig** [comment]
Which type of DHT sensor do you have (DHT11 vs DHT22) and where did you buy it? Make sure you have a 4.7k pull-up between the data line and VDD.


![Sample Wiring Sketch](http://www.einplatinencomputer.com/wp-content/uploads/2016/01/DHT22_Steckplatine-709x1024.png)

**Comment by mwittig** [comment]
See also https://forum.pimatic.org/topic/2404/important-note-for-pimatic-dht-sensors
